 services:
    xchanger:
        build:
          context: .
          dockerfile: Dockerfile
        env_file:
        # create this file yourself!
          - .env
        volumes:
         - ./config/xchanger:/app/configs